config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'game#index'

  resources :game, only: [:index, :show, :create] do
    post :hit, on: :member
    post :stop, on: :member
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/card.rb
class Card < ApplicationRecord
  has_and_belongs_to_many :games
  has_and_belongs_to_many :hands # that bad :(


  class << self
    def create_cards
      [:clubs, :diamonds, :spades, :hearts].each do |suit|
        
        (2..10).each do |number|
          create(suit: suit, value: number, name: number.to_s)
        end
        
        ['J', 'Q', 'K'].each do |name|
          create(suit: suit, value: 10, name: name)
        end
        
        create(suit: suit, value: 11, name: 'A')
      end
    end
  end

  def to_s
    "#{suit} : #{name}"
  end
end

app/models/deck.rb
class Deck < ApplicationRecord
  belongs_to :game, optional: true
  has_and_belongs_to_many :cards

  after_create :add_and_shuffle_cards

  def take_card
    card = cards.order("created_at DESC").last
    cards.delete(card.id)
    card
  end


  def add_and_shuffle_cards
    cards << Card.all.order('random()')
  end
end

app/models/game.rb
class Game < ApplicationRecord
  has_many :hands, dependent: :destroy
  has_one :deck, dependent: :destroy
  belongs_to :winner, class_name: User, optional: true

  STATUS = ['Идет', 'Подебил дилер', 'Победил игрок']

  after_create :create_deck
  after_create :create_dealer


  def add_user(user)
    unless hands.exists?(user_id: user.id)
      hand = Hand.create(type_name: 'Player', user_id: user.id)
      hands << hand
      2.times { hit_hand hand }
    end

  end

  def players_hands
    hands.where(type_name: 'Player')
  end

  def hit_hand(hand)
    create_new_deck_if_need
    message = hand.hit
    stop
    message
  end

  def hit_user(user)
    hit_hand(player_hand(user))
  end

  def play_dealer
    create_new_deck_if_need
    dealer_hand.play_dealer unless players_hands_with_score_less_22.empty?
  end

  def player_hand(user)
    hands.find_by(user_id: user.id, type_name: 'Player')
  end

  def dealer_hand
    hands.find_by(type_name: 'Dealer')
  end

  def hit_dealer
    create_new_deck_if_need
    dealer_hand.hit
  end

  def players_hands_with_score_less_22
    players_hands.map { |player| player if player.score < 22 }
  end


  def stop
    if can_find_winner?
      play_dealer
      winner = find_winner
      if winner
        if winner.type_name == 'Player'
          update_column(:winner_id, winner.user.id) if winner
          update_column(:status, STATUS[2])
        else
          update_column(:status, STATUS[1])
        end
      else
        push
      end
    end
  end

  def can_find_winner?
    !players_hands.exists?(status: Hand::STATUS[0]) || players_hands_with_score_less_22.empty?
  end

  # return nil if need push
  def find_winner
    _players_hands = players_hands_with_score_less_22
    if _players_hands.empty? || _players_hands.all?(&:blank?)
      update_column(:status, STATUS[1])
      return dealer_hand
    else
      player_max_score = _players_hands.max{ |p1, p2| p1.score <=> p2.score }.score
      return dealer_hand if dealer_hand.score > player_max_score && dealer_hand.score < 22
      players_hands.each {|hand| hand.update_column(:status, Hand::STATUS[3]) if hand.score < player_max_score }
      winners = players_hands.map {|h| h if h.score == player_max_score}
      if winners.size == 1
        winners[0]
      else
        nil
      end
    end
  end

  def push
    create_new_deck_if_need
    hands.find_each(:status, Hand::STATUS[0]) do |hand|
      hand.cards.delete_all
    end
    2.times {
      hit_dealer
      players_hands.each {|h| hit_hand(h)}
    }
  end


  def create_new_deck_if_need
    create_deck if deck.cards.size == 0
  end

  private

  def create_dealer
    dealer = Hand.create(type_name: 'Dealer')
    hands << dealer
    2.times { dealer.hit }
  end

end

app/models/hand.rb
class Hand < ApplicationRecord
  STATUS = ['play', 'stand', 'out', 'loose'].freeze
  has_and_belongs_to_many :cards
  belongs_to :game, optional: true
  belongs_to :user, optional: true

  # not good, need refactoring
  def hit
    if status == STATUS[0]
      case score
        when 0..19
          cards << game.deck.take_card
          if score == 21
            update_column(:status, STATUS[1])
            'Black Jack'
          elsif score > 21
            update_column(:status, STATUS[2])
            'You out'
          else
            'New card is tacked'
          end
        when 21
          'Ypu already have a Black Jack! Dont need for more cards!'
        else
          'Cant hit, score more than 21'
      end
    else
      "You cant hit, status is #{status}"
    end
  end

  def stand
    update_column(:status, STATUS[1])
  end

  def out
    update_column(:status, STATUS[2])
  end

  def score
    cards.sum(:value)
  end

  def play_dealer
    if score < 17
      hit
      play_dealer
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/game_controller.rb
class GameController < ApplicationController
  before_action :load_game, only: [:show, :hit, :stop]

  layout false, only: [:hit, :stop]


  def index
    @games = Game.all
  end

  def show
    if user_signed_in?
      @game.add_user current_user
    end
  end

  def create
    @game = Game.create
    redirect_to game_path(@game)
  end

  def hit
    @hand = @game.player_hand(current_user)
    @message = @game.hit_user(current_user)
  end

  def stop
    @game.player_hand(current_user).update_column(:status, Hand::STATUS[1])
    @game.stop
    @status = @game.status
  end

  private

  def load_game
    @game = Game.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/game_helper.rb
module GameHelper
end

app/views/game/_cards.haml
.row
  .col-md-2
    Карты:
  .col-md-9.col-md-offset-1
    - cards.each do |card|
      %strong= "#{card}"

app/views/game/_dealer.haml
%strong Дилер:
.row
  .col-md-12
    %strong
      Счет дилера:
      %em= "#{@game.dealer_hand.score}"
.row
  .col-md-2
    Карты:
  .col-md-9.col-md-offset-1
    - @game.dealer_hand.cards.each do |card|
      %strong= "#{card}"

app/views/game/_hand.haml
.row
  .col-md-12
    - if hand.user == current_user
      %strong Вы
    - else
      %strong= "Игрок: #{hand.user.email}"

.row
  .col-md-12
    %strong= "Статус: #{hand.status}"

.row
  .col-md-12
    %strong
      счет:
      %em= "#{hand.score}"
.row
  .col-md-2
    Карты:
  .col-md-9.col-md-offset-1
    - hand.cards.each do |card|
      %strong= "#{card}"

app/views/game/_hands.haml
.row
  .col-md-12
    - @game.players_hands.each do |hand|
      .row
        .col-md-12
          %div{ id: "hand_#{hand.id}"}
            = render partial: 'hand', locals: {hand: hand}
      %br

app/views/game/hit.js.erb
hand_id = '<%= "#hand_#{@hand.id}" %>';
$(hand_id).html("<%= escape_javascript(render partial: 'hand', locals: { hand: @hand } ) %>");
alert("<%= @message %>");

app/views/game/index.haml
%br
.row
  .col-md-12
    - @games.find_each do |game|
      .row
        .col-md-3
          %strong= "Игра id №: #{game.id}"
        .col-md-6
          %strong= "#{game.status}"
        .col-md-3
          - if game.status == Game::STATUS[0]
            - link_name = user_signed_in? ? 'Присоединиться' : 'Посмотреть'
            = link_to link_name, game_path(game)

app/views/game/show.haml
.row
  .col-md-12
    %h1 Новая игра

.row
  .col-md-12
    %h2#status= @game.status


  .row
    #dealer.col-md-12
      = render partial: 'dealer'
  %br
  .row
    .col-md-12
      %strong Игроки:

  %br

  #players
    = render partial: 'hands', locals: { game: @game }


  %br

  - if user_signed_in?
    #buttons.row
      .col-md-6
        = form_tag(hit_game_path(@game), method: :post, remote: true) do
          %input.btn.btn-primary{:value => "Еще карту", :type => "submit"}

      .col-md-6
        = form_tag(stop_game_path(@game), method: :post, remote: true) do
          %input.btn.btn-warning{:value => "Хватит", :type => "submit"}

app/views/game/stop.js.erb
$("#dealer").html("<%= escape_javascript(render partial: 'dealer' ) %>");

$("#status").html("<%= @status %>");
alert("<%= @status %>");

app/views/layouts/application.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title BlackJack
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    %nav.navbar.navbar-inverse
      .container
        .navbar-header
          = link_to 'На главную', root_path, :class => 'navbar-brand'
        #navbar.navbar-collapse.collapse
          %ul.nav.navbar-nav
            %li= link_to 'Начать новую игру', game_index_path, :method => :post if user_signed_in?
          %ul.nav.navbar-nav.navbar-right
            - if user_signed_in?
              %li= link_to('Мой аккаунт', edit_user_registration_path)
              %li= link_to ('Выйти'), destroy_user_session_path, :method => :delete
            - else
              %li= link_to('Войти', new_user_session_path)
              %li= link_to('Зарегестрироваться', new_user_registration_path)

    .container
      .row
        .col-md-8.col-md-offset-2
          %p.notice= notice
          %p.alert= alert

      %br
      .row
        .col-md-8.col-md-offset-2
          = yield